server:
  port: 8081  # 服务端口

spring:
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8

  datasource:  # mysql数据源配置
    driver-class-name: com.mysql.cj.jdbc.Driver
    # 推荐使用serverTimezone=Asia/Shanghai 也可用serverTimezome=GMT%2B8，但可能会无法识别
    url: jdbc:mysql://localhost:3306/guli?useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Shanghai
    username: root
    password: 123456
    hikari:
      connection-test-query: SELECT 1
      connection-timeout: 60000
      idle-timeout: 500000
      max-lifetime: 540000
      maximum-pool-size: 12
      minimum-idle: 10
      pool-name: GuliHikariPool
    type: com.zaxxer.hikari.HikariDataSource

# mybatis日志
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  mapper-locations: classpath:tech/jinguo/service/*/mapper/*x.xml
  global-config:
    db-config:
      logic-delete-value: 1
      logic-not-delete-value: 0

